# Generated by Django 5.1.2 on 2024-11-23 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0002_alter_mailing_options_alter_message_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailingattempt",
            options={"verbose_name": "Попытка рассылки", "verbose_name_plural": "Попытки рассылки"},
        ),
        migrations.AlterField(
            model_name="mailing",
            name="message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="mailing.message", verbose_name="Сообщение"
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="recipients",
            field=models.ManyToManyField(to="mailing.recipient", verbose_name="Получатели"),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="send_time_end",
            field=models.DateTimeField(verbose_name="Дата и время окончания отправки"),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="send_time_start",
            field=models.DateTimeField(verbose_name="Дата и время начала отправки"),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="status",
            field=models.CharField(
                choices=[("created", "Создана"), ("started", "Запущена"), ("finished", "Завершена")],
                default="created",
                max_length=10,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="mailingattempt",
            name="mailing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attempts",
                to="mailing.mailing",
                verbose_name="Рассылка",
            ),
        ),
        migrations.AlterField(
            model_name="mailingattempt",
            name="server_response",
            field=models.TextField(verbose_name="Ответ почтового сервера"),
        ),
        migrations.AlterField(
            model_name="mailingattempt",
            name="status",
            field=models.CharField(
                choices=[("success", "Успешно"), ("failed", "Не успешно")], max_length=7, verbose_name="Статус"
            ),
        ),
        migrations.AlterField(
            model_name="mailingattempt",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата и время попытки"),
        ),
    ]
